<!DOCTYPE html>
<html>
<head>
    <title>Zetabud</title>
    <link rel="stylesheet" type="text/css" href="/css/style.css"/>
    <script type="text/javascript" src="/js/jquery-1.5.min.js"></script>
    <script type="text/javascript" arc="/js/jquery.color.js"></script>
    <script type="text/javascript" src="/js/script.js"></script>
</head>
<body>
    <?php echo $this->layout()->content; ?>
    <?php echo $this->messages; ?>
</body>
</html>
