<!DOCTYPE html>
<html>
<head>
    <title>Zetabud</title>
    <link rel="stylesheet" type="text/css" href="/css/style.css"/>
    <script type="text/javascript" src="/js/jquery-1.5.min.js"></script>
    <script type="text/javascript" arc="/js/jquery.color.js"></script>
    <script type="text/javascript" src="/js/script.js"></script>
</head>
<body>
    <div id="contentwrapper">
        <header>
            Zetabud
        </header>
        <div id="appspace">
            <?php echo $this->layout()->content; ?>
        </div>
        <div id="launcher">
            <!-- Dynamically generate these links -->
            <a href="/app/foo">App</a>
            <a href="/login">Login</a>
        </div>
    </div>
</body>
</html>
