<?php
// This file generated by Propel 1.5.6 convert-conf target
return array (
  'BaseUser' => 'zetabud/om/BaseUser.php',
  'BaseUserPeer' => 'zetabud/om/BaseUserPeer.php',
  'BaseUserQuery' => 'zetabud/om/BaseUserQuery.php',
  'User' => 'zetabud/User.php',
  'UserPeer' => 'zetabud/UserPeer.php',
  'UserQuery' => 'zetabud/UserQuery.php',
  'UserTableMap' => 'zetabud/map/UserTableMap.php',
);