<?php
// This file generated by Propel 1.5.6 convert-conf target
// from XML runtime conf file /home/dan/www/zetabud/application/config/propel/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'zetabud' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=zetabud',
        'user' => 'zetabud',
        'password' => 'zetabud',
        'classname' => 'PropelPDO',
      ),
    ),
    'default' => 'zetabud',
  ),
  'generator_version' => '1.5.6',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-zetabud-conf.php');
return $conf;